library(datasets)
zipFileUrl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
if (file.exists("powerconsumption.zip")) {
	download.file(zipFileUrl, destfile="powercomsumption.zip", method="curl")
	unzip("powercomsumption.zip")
}
data <- read.table('household_power_consumption.txt', sep=';', header=TRUE)
data$DateTime <- paste(data$Date, data$Time, sep=' ')
data[["Date"]] <- as.Date(data[["Date"]], format="%d/%m/%Y")
datasub <- subset(data, Date>="2007-02-01" & Date <="2007-02-02")
datasub[["DateTime"]] <- strptime(datasub[["DateTime"]], format="%d/%m/%Y %H:%M:%S")
GlobalActivePower <- as.numeric(as.character(datasub$Global_active_power))
plot(datasub[["DateTime"]], GlobalActivePower, xlab="", ylab="Global Active Power (kilowatts)", type="n")
lines(datasub[["DateTime"]], GlobalActivePower)
dev.copy(png, "plot2.png", width=480, height=480, units="px", bg="white", col="black")
dev.off()
rm(data)
rm(datasub)
rm(GlobalActivePower)
rm(zipFileUrl)